apiVersion: v2
name: test-helm-charts-template
type: application
description: This is a helm charts template
maintainers:
  - name: DevOps
version: 1.0.1
appVersion: 0.1.3
icon: https://lido.fi/icon.png
