name: test-app
team: test-team
env: test-env

deployment:
  enabled: true
  annotations:
    custom-annotation: "true"

replicas: 3
terminationGracePeriodSeconds: 40

securityContext:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
  readOnlyRootFilesystem: true

serviceAccount:
  name: test-sa

image:
  name: docker.io/test-image
  tag: v1.2.3

resources:
  limits:
    cpu: "500m"
    memory: "128Mi"
    ephemeral-storage: "1Gi"
  requests:
    cpu: "250m"
    memory: "64Mi"
    ephemeral-storage: "512Mi"

maxSurge: 2
maxUnavailable: 2

service:
  enabled: true
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8081
    - name: metrics
      port: 9100
      targetPort: 9100

servicemonitor:
  endpoints:
    - interval: 15s
      path: /metrics
      port: metrics
      scheme: http

pvc:
  enabled: true

pvcs:
  - name: data
    accessModes:
      - ReadWriteOnce
    size: 100Mi
    storageClass: longhorn-standard

volumes:
  - name: data
    persistentVolumeClaim:
      claimName: data

ingress:
  enabled: true
  ingressClassName: nginx
  rules:
    - host: test.local
      paths:
        - path: /test
          pathType: Prefix
  tls:
    - hosts:
        - test.local
      secretName: test-tls

PodDisruptionBudget:
  enabled: true
  maxUnavailable: 2

HorizontalPodAutoscaler:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  averageUtilization: 75

containers:
  - name: container-1
    image:
      name: docker.io/test-image
      tag: v1.3.0
    command:
      - /bin/sh
      - -ec
    args:
      - . /vault/secrets/app && exec /app/start.sh
    startupProbe:
      httpGet:
        path: /healthz
        port: 8081
      failureThreshold: 2
      periodSeconds: 5
    readinessProbe:
      httpGet:
        path: /ready
        port: 8081
      failureThreshold: 2
      periodSeconds: 5
    livenessProbe:
      httpGet:
        path: /live
        port: 8081
      failureThreshold: 2
      periodSeconds: 5
    volumeMounts:
      - name: data
        mountPath: /data
    env:
      - name: FEATURE_X_ENABLED
        value: "true"
      - name: NUMERIC_STRING
        value: "42"

cronjobs:
  - name: test-cronjob
    schedule: "*/5 * * * *"   # every 5 minutes
    restartPolicy: Never
    containers:
      - name: container-1
        image:
          name: docker.io/test-image
          tag: v1.3.0
          # name: busybox
          # tag: "1.37.0"
        command: ["/bin/sh", "-c"]
        args:
          - date; echo "Hello from container one"
        resources:
          requests:
            cpu: 10m
            memory: 16Mi
          limits:
            cpu: 50m
            memory: 32Mi
